vich_uploader:
    db_driver: orm

    mappings:
        report_document:
            uri_prefix: /documents/reports
            upload_destination: '%kernel.project_dir%/public/documentss/reports'
            namer: Vich\UploaderBundle\Naming\SmartUniqueNamer

    #mappings:
    #    products:
    #        uri_prefix: /images/products
    #        upload_destination: '%kernel.project_dir%/public/images/products'
