vich_uploader:
    db_driver: orm

    mappings:
        report_document:
            uri_prefix: /documents/reports
            upload_destination: '%kernel.project_dir%/public/documents/reports'
            namer: Vich\UploaderBundle\Naming\SmartUniqueNamer
        newspaper_document:
            uri_prefix: /documents/newspapers
            upload_destination: '%kernel.project_dir%/public/documents/newspapers'
            namer: Vich\UploaderBundle\Naming\SmartUniqueNamer
        content_picture:
            uri_prefix: /pictures/content
            upload_destination: '%kernel.project_dir%/public/pictures/content'
            namer: Vich\UploaderBundle\Naming\SmartUniqueNamer
        event_picture:
            uri_prefix: /pictures/event
            upload_destination: '%kernel.project_dir%/public/pictures/event'
            namer: Vich\UploaderBundle\Naming\SmartUniqueNamer
        teammate_picture:
            uri_prefix: /pictures/teammate
            upload_destination: '%kernel.project_dir%/public/pictures/teammate'
            namer: Vich\UploaderBundle\Naming\SmartUniqueNamer
        card_picture:
            uri_prefix: /pictures/card
            upload_destination: '%kernel.project_dir%/public/pictures/card'
            namer: Vich\UploaderBundle\Naming\SmartUniqueNamer

    #mappings:
    #    products:
    #        uri_prefix: /images/products
    #        upload_destination: '%kernel.project_dir%/public/images/products'
